### ISSUE TITLE
Detect PHPUnit requirements and use the right config file

### ISSUE THREAD

**Issue by juampynr** [Lullabot/drupal9ci#27]
Sites using Drupal 8.5 need to replace the phpunit.xml file with the respective version of it for this core release. See https://github.com/Lullabot/drupal8ci#class-drupaltestslistenersdrupalstandardslistener-does-not-exist.

It would be better if the installer checks if `\Drupal\Tests\Listeners\DrupalStandardsListener` exists and then decides which phpunit.xml file to use.

**Comment by esolitos** [comment]
It's many times that i forget to switch the 8.5+ config file, perhaps at this point (9+ is out) only 8.59 should be supported by default?

**Comment by juampynr** [comment]
Hi @esolitos ! Sure, this makes sense. I am not sure when I will find the time to make the adjustment though.

**Comment by juampynr** [comment]
This is not a problem any more because we are way passed Drupal 8.5.
