### ISSUE TITLE
Increase the ImageMagic max image dimensions

### ISSUE THREAD

**Issue by quicksketch** [Lullabot/drupal9ci#43]
When a test failure occurs, Behat tries to take a screenshot of the failure. A screenshot is captured for every step of the test, and then concatenated together into one big image. These large images can easily exceed the maximum image dimensions for ImageMagick. We should increase this to a very large value by default.

This value can be modified in `/etc/ImageMagick-6/policy.xml`, e.g.

```
  <policy domain="resource" name="width" value="10MP"/>
  <policy domain="resource" name="height" value="200MP"/>
```

**Comment by quicksketch** [comment]
For the time being I've added this to bump up the default in a simple find/replace method:
```
  before_script:
    - sed -i -e "s/16KP/200MB/" /etc/ImageMagick-6/policy.xml
```

**Comment by deviantintegral** [comment]
I'm closing this given there's been no movement in several years.
