### ISSUE TITLE
Annotations for code-standards

### ISSUE THREAD

**Issue by guix77** [Lullabot/drupal9ci#50]
Hi,

Unless I'm making a mistake, there are no annotations for code-standards. Which means that when it fails, there's no report of the actual code-standards issues.

Would be nice to have :)

**Comment by fjgarlin** [comment]
What do you mean exactly? I got the output to show by default. Here is an example of a failing coding standard check where I can see the output of what's failing: https://travis-ci.com/github/fjgarlin/d9-lagoon/jobs/496434366

**Comment by guix77** [comment]
With annotations, lint problems are directly reported to GitHub so you don't have to go through the job log. Example: https://github.com/guix77/d8sandbox/actions/runs/178143997

Feel free to close this issue, on my side I created my own GitHub action: https://github.com/guix77/phpcs-drupal-action
