### ISSUE TITLE
Changes to upstream image causes CircleCI to break

### ISSUE THREAD

**Issue by m4olivei** [Lullabot/drupal9ci#52]
It looks like the upstream Drupal image changed such that it's causing the CircleCI job to fail on master:

https://circleci.com/gh/Lullabot/drupal8ci/106?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

In the same way our site project that uses the `juampynr/drupal8ci:latest` image is failing.

I believe it has to do with this change, which changed the working directory among other things:

https://github.com/docker-library/drupal/pull/176

**Comment by deviantintegral** [comment]
I think this has been fixed so closing this one out.
