### ISSUE TITLE
Run Travis CI in a Drupal Docker project

### ISSUE THREAD

**Issue by sleepinzombie** [Lullabot/drupal9ci#57]
I have a Drupal 8 project running in a Docker. But I am having a doubt about how to make the CI works.
Normally, I know that the `.travis.yml` file should resides in the root of my repo, however my Drupal project resides in a `webroot` folder (See attached image).

Due to the fact that the `.travis.yml` file is not in the root of the repo, the build always failed.

Any help would be highly appreciated.
<img width="348" alt="Screenshot 2021-01-16 at 2 59 55 AM" src="https://user-images.githubusercontent.com/39788411/104786649-edc17b80-57a6-11eb-9179-0d349f391ed1.png">

**Comment by juampynr** [comment]
Hi @sleepinzombie !

I think that you could make it work by modifying the paths at `docroot/.travis.yml`. However, what is the main reason for you to put the `.travis.yml` under docroot? If you move and adjust `docroot/.travis.yml` to the root of the repository, then you could run the installer mentioned at https://github.com/Lullabot/drupal8ci#travis-ci to get the foundation to start doing CI.

**Comment by sleepinzombie** [comment]
Hello @juampynr, I hope you are fine! Thank you for the reply.
Actually, in my Docker, I don't have Composer installed at the root. Composer and all the PHP dependencies are installed in the `webroot` folder. However, I will it a try and revert back.

**Comment by juampynr** [comment]
OK! Let us know how it goes.
