### ISSUE TITLE
Drupal 9 compatibility

### ISSUE THREAD

**Issue by fjgarlin** [Lullabot/drupal9ci#64]
Trying this out of the box into a Drupal 9 project brings a lot of issues.

It'd be great to update for Drupal 9 compatibility. Perhaps `9.x` branch or similar. If we get this to work then maybe the repo could be renamed to `drupal-ci` or similar.

I've started some work on it on the Travis side, so I'll open a PR to address this. I'm not super familiar with CI tools so any feedback/comments are appreciated.

**Comment by juampynr** [comment]
Thanks @fjgarlin! That pull request looks great.

**Comment by juampynr** [comment]
@fjgarlin this is done, right?

**Comment by fjgarlin** [comment]
I'd say so.

Most of it done on:
* https://github.com/Lullabot/drupal9ci/pull/65
* https://github.com/Lullabot/drupal9ci/pull/66

Only gitlab left to fully test but I'd say the bulk of the D9 integration is done already.

**Comment by fjgarlin** [comment]
As a way of follow up on this issue. D9 for Gitlab CI: https://github.com/Lullabot/drupal9ci/pull/68
