### ISSUE TITLE
Replace Behat tests by Cypress.io ones

### ISSUE THREAD

**Issue by juampynr** [Lullabot/drupal9ci#67]
Cypress.io's developer experince is much better than Behat's. Among other things:

* Does not neet Chromedriver.
* Takes screenshots and records clips by default.
* Provides an app to view tests in action and debug them LIVE.
* Has great documentation.
* Has a browser plugin to record steps and export them.
* It's written in JavaScript, which makes them more accessible to front end devs too.

**Comment by fjgarlin** [comment]
As part of working on this, we will need to have `npm` available. I guess it should be added here `juampynr/drupal8ci` as that's the base image. Perhaps use the opportunity to call it `juampynr/drupal9ci`.

**Comment by juampynr** [comment]
@fjgarlin done!

https://hub.docker.com/r/juampynr/drupal9ci/tags?page=1&ordering=last_updated

**Comment by juampynr** [comment]
It builds from Dockerfile9, which is at the root of this repository. It also adds node which adds npm too.

**Comment by fjgarlin** [comment]
This is awesome! Thanks 💪
